// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-services.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var list_services_default = defineTool({
  name: "list_services",
  title: "List dental services",
  description: "List clinical services offered by Muhazi Dental Clinic (name, category, description).",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter (e.g. 'general', 'cosmetic').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("services").select("id,name,category,description").order("name");
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-doctors.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_doctors_default = defineTool2({
  name: "list_doctors",
  title: "List dentists",
  description: "List active dentists and clinical staff visible on the public website.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("staff").select("id,full_name,role,specialization,bio,photo_url").eq("is_active", true).order("full_name").limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { doctors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-announcements.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var list_announcements_default = defineTool3({
  name: "list_announcements",
  title: "List clinic announcements",
  description: "List currently active public announcements from Muhazi Dental Clinic.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("announcements").select("id,title,message,type,created_at").eq("is_active", true).order("created_at", { ascending: false }).limit(20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { announcements: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/clinic-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
var clinic_info_default = defineTool4({
  name: "clinic_info",
  title: "Muhazi Dental Clinic info",
  description: "Return contact, location, and working hours for Muhazi Dental Clinic.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Muhazi Dental Clinic",
      location: "Rwamagana, Rwanda",
      phone: "+250 787 630 399",
      website: "https://muhazi.lovable.app",
      hours: "Open daily 8:00 AM \u2013 8:00 PM",
      booking_url: "https://muhazi.lovable.app/book",
      languages: ["English", "Kinyarwanda", "French"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "muhazi-dental-mcp",
  title: "Muhazi Dental Clinic",
  version: "0.1.0",
  instructions: "Tools for Muhazi Dental Clinic. Use `clinic_info` for hours/contact, `list_services` for clinical services, `list_doctors` for dentists, and `list_announcements` for current notices.",
  tools: [clinic_info_default, list_services_default, list_doctors_default, list_announcements_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
